site_name: Benjamin Daniels
theme:
    name: material
    palette:
        primary: 'teal'
        accent: 'teal'
    logo:
        icon: memory
    font:
        text: 'Fira Sans'
        code: 'Fira Mono'

markdown_extensions:
  - codehilite:
      linenums: true
